from state import AgentState

def outreach_node(state: AgentState) -> dict:
    """
    Agent 4: Drafts the final penalty notice email using the gap analysis report 
    and the CSO contact info.
    """
    print(f"--- [Agent 4] Drafting compliance outreach for {state.get('company_name')} ---")
    
    # Safely get the data from the previous agents
    cso_info = state.get("cso_contact_info") or {"name": "Compliance Officer", "email": "Legal Department"}
    gap_analysis = state.get("compliance_gap_analysis", "No gap analysis found.")
    company = state.get("company_name", "your organization")
    
    # Draft the official notice
    email_draft = f"""
SUBJECT: URGENT - Regulatory Compliance Breach Notice (MoEFCC)
TO: {cso_info.get('email')}
ATTN: {cso_info.get('name')}, Chief Sustainability Officer

Dear {cso_info.get('name')},

Our automated environmental monitoring systems have flagged a critical compliance breach regarding the recent ESG disclosures for {company}.

Please review the audit summary below:

{gap_analysis}

ACTION REQUIRED:
Under the Mandatory Decarbonization and Emission Cap Rules, you are required to arrange for the settlement of the estimated financial exposure within 30 days. Please contact the MoEFCC regulatory board immediately to initiate remediation.

System generated by XL Ventures AI Compliance Framework.
    """
    
    return {
        "final_outreach_draft": email_draft.strip(),
        "next_step": "end" # Tells LangGraph to stop execution
    }